### ISSUE TITLE
Boavizta - Shift collaboration 

### ISSUE THREAD

**Issue by bharno** [mlco2/codecarbon#113]
Hello CodeCarbon team

I was reading your 'call for action' page and I think we could have a discussion together with a working group in France I'm contributing to (https://www.boavizta.org - in French sorry). I'm also a contributor to the Shift project for their 'Digital sobriety report ' (https://theshiftproject.org/article/deployer-la-sobriete-numerique-rapport-shift/ the last one soon to be translated).

One common topic we have for instance is the world electricity mix I believe you are trying to evaluate on the full scope (inc upstream-downstream effects) : is someone of your team would be ok for a chat in the coming weeks ?

Thanks
Arnaud Gueguen

**Comment by vict0rsch** [comment]
Hi Arnaud, I'm sorry we missed out on your message. We're actually jsut starting a collaboration with DataForGood if you were interested to jump in! https://dataforgood-fr.medium.com/lancement-de-la-saison-9-data-for-good-1a19063433c6#2370

Otherwise feel free to contact me at <schmidtv at mila dot quebec>

**Comment by benoit-cty** [comment]
We have made a call with Boavizta and Scaphandre in may. We sure have to collaborate more on the topic.
