### ISSUE TITLE
Wrong computation of carbon intensity

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#211]
* CodeCarbon version: 1.2.0
* Python version: 3.8
* Operating System: Ubuntu 20.04

### What I did

I've added a log (in https://github.com/mlco2/codecarbon/pull/210) of the carbon intensity and I got:
```
We apply an energy mix of 0.424584 Kg.CO2eq/kWh for France
```

### What I expect

The France carbon intensity is 34 g.CO2eq/kWh, not 424.

### Way to solve it

In https://github.com/mlco2/codecarbon/blob/be3c6046e1294d91ccecfa7e5de3a6369152de8e/codecarbon/core/emissions.py#L172 I think we do not use the parameter `lowCarbon` of the energy mix, so the result of carbon intensity is wrong.

**Comment by bouffan** [comment]
So I have been looking into that, and I don't think this is a bug of the code. 

The main problem is that in the current form, the energy mix that is retrieved from France is the following dictionary

emissions_mix = {'lowCarbon': 4.7973573649744, 'naturalGas': 1.6299605210559, 'petroleum': 3.406617337, 'coal': 0.3164766775216, 'total': 10.150411900552}

Then, the way the code is written is such that the energy has to be divided among the possible energy sources contained in the energy mix dictionary, which translates in the percentage:

emissions_percentage = {'lowCarbon': 0.4726268659810259, 'naturalGas': 0.1605807268734838, 'petroleum': 0.33561370419014636, 'coal': 0.031178702955334196}

The big problem here is that it means that here, we try to produce our 1kWh energy ONLY with these 4 sources. But, especially in France, a lot of the energy is coming from other sources that produce much less CO2 (i.e nuclear and hydro). 
If you look at https://youmatter.world/fr/co2-kwh-electricite-france-mix-electrique/ , you can see that they give a "broad" estimate of the percentage where ~77% is created by nuclear energy that only produces 12 g of eqCO2 per kWh (compared to the 995, 816 and 743 eqCO2 per kWh for coal,petroleum and naturalGas currently defined in the code).

So this is the reason why the France carbon intensity is very high because we try to produce our 1kWh only with very polluting form of energy.

Just as an example, I tried to hard code the percentage of mix energy for france adding nuclear and hydro (using values from https://youmatter.world/fr/co2-kwh-electricite-france-mix-electrique/) as 

emissions_percentage={'coal': 0.018, 'naturalGas': 0.077, 'petroleum': 0.007, "nuclear": 0.716, "hydro":0.101}

with the conversion factor coming from https://youmatter.world/fr/co2-kwh-electricite-france-mix-electrique/ and https://www.rte-france.com/eco2mix/les-emissions-de-co2-par-kwh-produit-en-france,

emissions_by_source = {
            "coal": EmissionsPerKwh.from_kgs_per_kwh(0.986),
            "petroleum": EmissionsPerKwh.from_kgs_per_kwh(0.777),
            "naturalGas": EmissionsPerKwh.from_kgs_per_kwh(0.429),
            "nuclear": EmissionsPerKwh.from_kgs_per_kwh(0.012),
            "hydro": EmissionsPerKwh.from_kgs_per_kwh(0.024)
        }

and in this case i find that the France carbon intensity is 67 g.CO2eq/kWh. Not perfect but closer!

**Comment by benoit-cty** [comment]
Thank very much !

It means that we have to change all the data file and the way we process it... @vict0rsch how the data file was build ?

"lowCarbon" does not include nuclear and hydro ? You're right, even if it's the case, it's wrong at least for France.

**Comment by vict0rsch** [comment]
I'm not sure I remember exactly. From what I can remember it was a 2017 average created in 2018 by Tmrow in their electricitymap contrib repo https://github.com/tmrowco/electricitymap-contrib/blob/master/config/co2eq_parameters.json but it looks like it has changed.

@bouffan was proposing to use https://ourworldindata.org/grapher/per-capita-energy-stacked?country=USA~GBR~OWID_WRL~CHN~IND~FRA~DEU~SWE~ZAF~JPN~BRA which seems like a good alternative

**Comment by corradio** [comment]
Hi everyone, Olivier here, author of electricityMap.
Would it help if we gave you access to our data/API?
Note that as the API is also used for commercial access, we wouldn't allow publishing the API token, but any user would be able to write to us to get a token (we also plan to expand our free tier).

In any case, I'm happy to personally give a hand here to make sure you have correct numbers. Let me know how to help!

Olivier

**Comment by ngoterence** [comment]
Hi everyone, 

* There are two types of mixes: the energy mix and the electricity mix, which are completely different in the case of France. 

It looks like the wrong computation of the French carbon intensity is due to the fact that you use the energy mix, while the electricity mix should be more relevant here.

Indeed, your composition is quite similar to the pie chart presented at https://enerdigit.fr/mix-energetique/  (energy mix), whereas one would expect a partition closer to something like this : https://enerdigit.fr/mix-electrique/ (electricity mix)

* By the way, creating an Electricitymap API token is pretty straight forward for users,  inviting them to do so in the documentation or README could be helpful. As @corradio said, the tool might benefit a lot from Electricitymap’s data.
