### ISSUE TITLE
Are GCP emissions overstated b/c of missing CFE in calculation?

### ISSUE THREAD

**Issue by verdverm** [mlco2/codecarbon#483]
Looking at:

- https://github.com/mlco2/codecarbon/blob/master/codecarbon/core/emissions.py#L43C21-L43C21
- https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/cloud/impact.csv
- https://cloud.google.com/sustainability/region-carbon#understanding

I'm curious about the factors used in the calculation. It seems like my entire usage is calculated as if it was using only non-renewable energy. Based on the explanation of the data from the GCP page, it seems like the calculation should scale based on the CFE%

In particular, for the intensity value used in the calculation

> For regions that are similar in CFE%, this will indicate the relative emissions for when your workload is not running on carbon free energy.

Can you please clarify?

I think the following two data centers explained would help me to understand how things are calcluated

| Region | Location | CFE% | intensity |
| -- | -- | -- | -- |
| asia-southeast1 | Singapore | 4% | 372 |
|  us-central1 | Iowa | 92% | 445 |

From the code link & calculation, would Singapore produce a lower carbon value for the same workload, despite the quite opposite CFE%?

**Comment by benoit-cty** [comment]
Sorry for late answer.
Our CSV is 9 month old, and we do not use CFE% for calculation because the intensity already include the clean energy from the grid.
For example, for GCP Paris, the carbon intensity of 71 g.eq.CO2/kWh is the one of France, the "Google CFE%" of 87% probably mean that Google do nothing in France for cleaner energy because 87% is just nuclear + renewable of the French grid.
